### ISSUE TITLE
Не запускается 

### ISSUE THREAD

**Issue by Swityflox** [Dezodemius/Magic-Library#14]
При запуске выдает такую ошибку:
![image](https://user-images.githubusercontent.com/83553046/116924336-c9f84780-ac68-11eb-82a0-06fd247905f2.png)
а после чего закрывается.

вот логи:
[library.log](https://github.com/Dezodemius/Magic-Library/files/6417249/library.log)

**Comment by Dezodemius** [comment]
https://github.com/Dezodemius/Magic-Library/wiki/%D0%9D%D0%B0%D1%87%D0%B0%D0%BB%D0%BE-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B-%D1%81-Elasticsearch#%D0%9A%D0%B0%D0%BA-%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%82%D1%8C-%D0%BF%D0%BB%D0%B0%D0%B3%D0%B8%D0%BD%D1%8B
Попробуй установить плагины для Elasticsearch. Если инструкция непонятна, то создай отдельное Issue и выскажись как было бы лучше

**Comment by Dezodemius** [comment]
@Dezodemius , Нужно обрабатывать это исключение и писать понятную ошибку
